### ISSUE TITLE
Pint の読みについて

### ISSUE THREAD

**Issue by nshiro** [laravel-ja/ja-docs-9.x#11]
https://readouble.com/laravel/9.x/ja/pint.html

冒頭にある「Laravel Pint（パイント：体積の単位）」の件で、
開発した作者的には、「パイント」ではなく、「ピント」となるようです。

https://twitter.com/enunomaduro/status/1539714000547713027
作者の呟き
"Pint" comes from PHP + Lint.
I didn't even know what a Pint(beer) was before naming this tool.
I just say Pint like Lint. Not like p “eye” nt.

また、Youtube系の動画でも、「パイントではなく、ピント」と紹介されています。（動画の冒頭の方）
https://www.youtube.com/watch?v=dvxzuH2ds8A&t=22s
https://www.youtube.com/watch?v=5khyIHIYIK4&t=49s

本家ドキュメントに読み方の記載がある訳では無いので、どれが正解という事は無いかとは思いますが、
https://laravel.com/docs/9.x/pint
単位の「パイント」で紹介するより「ピント」で紹介した方がいいのかと思いました。

以上になります。
いつも翻訳ありがとうございます。

**Comment by HiroKws** [comment]
ありがとうございます。発音の説明をピントへ修正しました。現在、翻訳に使っている機械ではないため、readouble.comへの反映は月曜日になる予定です。
