### ISSUE TITLE
言語ファイルの内容不足について

### ISSUE THREAD

**Issue by nison-jp** [laravel-ja/ja-docs-9.x#23]
いつもお世話になっております。

[`validations.php`](https://readouble.com/laravel/9.x/ja/validation-php.html) 言語ファイルにおきまして、不足する言語行がございます。

v9.xの途中で、本体側では従来 `en.json` に入っていたパスワードバリデーションの設定内容が `validations.php` へ移動しています。(参照: https://github.com/laravel/laravel/commit/db0d052ece1c17c506633f4c9f5604b65e1cc3a4)
その内容は下記のとおりです。

```php
    'password' => [
        'letters' => 'The :attribute field must contain at least one letter.',
        'mixed' => 'The :attribute field must contain at least one uppercase and one lowercase letter.',
        'numbers' => 'The :attribute field must contain at least one number.',
        'symbols' => 'The :attribute field must contain at least one symbol.',
        'uncompromised' => 'The given :attribute has appeared in a data leak. Please choose a different :attribute.',
    ],
```

これら項目の訳文を指定しない場合、パスワードのバリデーションエラー時にメッセージが表示されません。

内容の是非はともかく、項目自体はカスタマイズのベースとして必要なのではないかと考えています。

言語ファイルは本リポジトリ内にございませんので、便宜上こちらで投稿させていただきました。

**Comment by HiroKws** [comment]
ご連絡ありがとうございます。

残念ながら、９xの日本語翻訳のメンテ期間は、Laravel本体に合わせていますので、セキュリティ的な脆弱性の対応以外はすでに行っていません。
また、Laravel言語ファイルの翻訳を専門に提供しているパッケージもあり、正直当サイトへの翻訳ファイルへのアクセスは多くありません。そのため、10.xからは提供を止めています。

ご心配されているエラーメッセージが出ないという点についましては、app設定ファイルのフォールバック言語をオリジナルのenのまま変更していなければ、英語で表示されるはずですので、不具合があれば開発者の方が自身で気がつくでしょう。緊急性はないと思います。

お気づきになられましたら、最新バージョンの翻訳や未翻訳などについても、
お知らせいただければ、ありがたいです。
